### ISSUE TITLE
Compatibility break for older logs

### ISSUE THREAD

**Issue by luis109** [LSTS/neptus#124]
Commit: 1f1cba7b03331466353c9b4e92eab08efa882cd5

Breaks compatibility with older logs. MRA can't index, stays stuck forever...
Works fine on the previous commit: a7860f821271a944442bb2772ec44acb98beaec2

![image](https://user-images.githubusercontent.com/44328942/104019979-5f506700-51b4-11eb-94d4-2424471f1841.png)

**Comment by paulosousadias** [comment]
This is related to this: https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

See commit f63d17ab2 with a temporary fix.

**Comment by paulosousadias** [comment]
java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;
	at pt.lsts.imc.lsf.BigByteBuffer.position(BigByteBuffer.java:78)
	at pt.lsts.imc.lsf.LsfIndex.createIndex(LsfIndex.java:493)
	at pt.lsts.imc.lsf.LsfIndex.checkIndex(LsfIndex.java:603)
	at pt.lsts.imc.lsf.LsfIndex.loadIndex(LsfIndex.java:255)
	at pt.lsts.imc.lsf.LsfIndex.load(LsfIndex.java:199)
	at pt.lsts.imc.lsf.LsfIndex.<init>(LsfIndex.java:207)
	at pt.lsts.neptus.util.llf.LsfLogSource.loadLog(LsfLogSource.java:147)
	at pt.lsts.neptus.util.llf.LsfLogSource.<init>(LsfLogSource.java:77)
	at pt.lsts.neptus.mra.MRAFilesHandler.openLSF(MRAFilesHandler.java:236)
	at pt.lsts.neptus.mra.MRAFilesHandler.openLog(MRAFilesHandler.java:128)
	at pt.lsts.neptus.mra.MRAMenuBar$1$1.run(MRAMenuBar.java:232)
