### ISSUE TITLE
Popup Preview throws exception

### ISSUE THREAD

**Issue by rasmartins** [LSTS/neptus#56]
I'm not sure what the PopUpPreview class does but it's not being loaded correctly because the class name is PopupPreview.

java.lang.ClassNotFoundException: pt.lsts.neptus.mp.maneuvers.PopUpPreview
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at pt.lsts.neptus.mp.preview.ManPreviewFactory.getPreview(ManPreviewFactory.java:81)
	at pt.lsts.neptus.mp.preview.SimulationEngine.simulationStep(SimulationEngine.java:128)
	at pt.lsts.neptus.mp.preview.PlanSimulationOverlay$1.run(PlanSimulationOverlay.java:102)

**Comment by paulosousadias** [comment]
Thanks. Fix at f8eaf39. This is the rough simulation of a pop up maneuver.
